### ISSUE TITLE
No hash added

### ISSUE THREAD

**Issue by andreasnymark** [texnixe/kirby-structure-id#1]
I’ve installed the plugin as instructed, but unfortunely no hash is added. On update, there’s still an empty `hash_id`. 

I’ve got another hook on `panel.page.update` in config, not sure if that might intervene. Removing it makes no difference. 

I’ve disabled all other plugins as well, without it making any difference.

I’m using Kirby 2.5.8 with Kirby Structure ID 1.2.1

**Comment by texnixe** [comment]
Could you post your blueprint and config settings, please? I just tested this in a fresh Starterkit and couldn't find any problems.

**Comment by andreasnymark** [comment]
Thanks.

I’ve removed almost everything, and it’s still not working. 

Config:

    c::set( 'license', 'put your license key here' );
    c::set( 'debug', true );
    c::set( 'cache', true );
    c::set( 'home', 'start' );
    c::set( 'tinyurl.enabled', false );
    c::set( 'tinyurl.folder', 'tiny' );

Blueprint:

    title: Page
    pages: false
    files: true
    fields:
      title:
        label: Page title
        type: text
        width: 1/2
      links:
        label: List of links
        type: structure
        style: table
        entry: >
          {{linkurl}}
        fields:
          hash_id:
            label: ID
            type: text
            readonly: true
          linkurl:
            label: Link
            type: url
          linkdesc:
            label: Description
            type: text
          linkstarred:
            label: Starred
            type: toggle
            text: on/off
            default: off

**Comment by texnixe** [comment]
Looks like you haven't defined the structure field settings in your config? You have to define an array of pages and structure field names, see the [readme](https://github.com/texnixe/kirby-structure-id#structureiddata). Otherwise the plugin does not know what to update.

Edit: I have just updated the readme to make this clearer.

**Comment by andreasnymark** [comment]
I see, thanks for helping out. The title had me confused, as you’ve already mentioned. Maybe change from "options" to "settings"?

What I tested early was using `'(:all)'` which is not working. Is there a workaround for that? Blueprint name instead of URI?

    c::set( 'structure.id.data', [
      '(:all)' => [ 'links' ]
    ]);

**Comment by texnixe** [comment]
`(:all)` by itself doesn't work, you can only use it together with a parent. If I use the blueprint name, I have to check the whole site for any pages that may or may not use a blueprint.

**Comment by texnixe** [comment]
Thanks for your feedback, @andreasnymark, I updated the readme again with your suggestions.

**Comment by bnomei** [comment]
i my case i am adding new 'projects' (with a stucture id filed in blueprint) on root level, but i now would have to add them all manually to config.

having the ability to process/watch (panel hook) all pages would fix that for me. please add support for `(:all)`. 🙏 

**suggestion**
https://github.com/texnixe/kirby-structure-id/blob/ad73cf0a28cf5941bd79efa52e3fb2e06ebae12e/kirby-structure-id.php#L41
```php
if($key == '(:all)') {
        foreach(kirby()->site()->index() as $child) {
          $expandedData[$child->uri()] = $value;
        }
      } else {
        $pattern = '!(\/)\(:([a-z]{3})\)!';
...
```

**Comment by texnixe** [comment]
@bnomei Thumbs down as motivation to add an option, seriously?

**Comment by bnomei** [comment]
@texnixe thanks for telling me. did emoji on mobile and. continued later on desktop. should have been thumbs up.

**Comment by texnixe** [comment]
Ok, all good 🙂.

Well, I see the use case and can - of course - add the option, especially as you were so nice as to give me the code ready to use, but you might end up with an endless list of pages, don't know if that is such a good idea? In your case, `(:any)` would be a better option, anyway, so the list would be limited to first level pages?

**Comment by texnixe** [comment]
I've added both options now.
