### ISSUE TITLE
custom generateHash function

### ISSUE THREAD

**Issue by bnomei** [texnixe/kirby-structure-id#2]
i would love to have a setting for a closure to hook into `generateHash()`. so i can use a different algorithm.

in my case [a shorter string](http://stackoverflow.com/questions/1846202/php-how-to-generate-a-random-unique-alphanumeric-string/13733588#13733588) but with additional verification.

**Comment by texnixe** [comment]
Good idea, I'll look into it asap.

**Comment by bnomei** [comment]
@pedroborges did something like that for his [meta tags plugin](https://github.com/pedroborges/kirby-meta-tags/blob/master/src/MetaTags.php#L39). maybe it helps as a starting point.

**Comment by texnixe** [comment]
Yes, I know, I already had a look at that plugin. Won't have time before the weekend, though, Kosmos time this week.

**Comment by bnomei** [comment]
**config.php**
```php
c::set('structure.id.generateHash', function() {
  return myHashGenerator();
});
```

**kirby-structure-id.php**
```
public function generateHash() {
    $hashID = md5(microtime().session_id());

    $callback = c::get('structure.id.generateHash');
    if(is_callable($callback)) {
      $hashID = (string) $callback();
    }

    return $hashID;
  }
```

**Comment by texnixe** [comment]
Looks good and looks as if you can't wait to have it, so here you go.

**Comment by fourpixels** [comment]
I am so out of PHP and just ignore me if I'm wrong, but how about reversing it?

```php
public function generateHash() {
    $callback = c::get('structure.id.generateHash');
    if (is_callable($callback)) {
        return (string) $callback();
    }

    return md5(microtime().session_id());;
}
```

Otherwise you may still create md5 that might not be used in any way? 😄 

p.s.
Oh crap, this is half year long, sorry for resurrecting it, I just got here by some links 😋
