### ISSUE TITLE
improving readme: field suggestions

### ISSUE THREAD

**Issue by bnomei** [texnixe/kirby-structure-id#3]
you could add some suggestions on how to use the field. but maybe its redundant since this plugin is most probably used by advanced kirby devs anyway.

- maybe providing a `placeholder` for the hash_id can be used to explain that the hash will be created when saving the content.
- also one could use field type `hidden` instead of `text` to hide the hash_id from panel.

**Comment by texnixe** [comment]
Thanks for your suggestions, just updated.
